### ISSUE TITLE
 Allowed memory size of nnnn bytes exhausted

### ISSUE THREAD

**Issue by LinkPool2** [TYPO3-Documentation/TYPO3CMS-Example-ExtensionManual#52]
Hi,
trying to send the command "abgeschlossene löschen" in TYPO3 BE I'll get;

`[24-Sep-2023 10:42:31] WARNING: [pool typo3-11] child 3446167 said into stderr: 
"NOTICE: PHP message: PHP Fatal error:  Allowed memory size of nnnn bytes exhausted (tried to allocate 20480 bytes)
 in typo3_src/typo3_src-11.5.30/typo3/sysext/extbase/Classes/DomainObject/AbstractDomainObject.php on line 218"
`
```
https://wwww.host.de/typo3/module/tools/TaskqueueTaskqueue?
token=53645615038777ecd70e161a5a6bae5b1f2fdb80
&tx_taskqueue_tools_taskqueuetaskqueue%5Baction%5D=deleteFinished
&tx_taskqueue_tools_taskqueuetaskqueue%5Bcontroller%5D=Task
```

At this moment our Taskq contains 102.480 tasks

```
    /**
     * action delete finished tasks
     *
     * @throws StopActionException
     * @throws UnsupportedRequestTypeException
     * @throws IllegalObjectTypeException
     */
    public function deleteFinishedAction(): void
    {
        $tasks = $this->taskRepository->findFinished();
        $this->addFlashMessageForDeletion($tasks);
        foreach ($tasks as $task) {
            $this->taskRepository->remove($task);
        }
        $this->redirect('list');
    }
```

Maybe it would be better so create & call a taskRepository->deleteFinished() Method.
Something like this - untested:

```
    /**
     * delete all finished tasks
     * @return int
     */
    public function deleteFinished(): int
    {
        $queryBuilder = $this->connectionPool->getQueryBuilderForTable('tx_taskqueue_domain_model_task');
        $affectedRows = $queryBuilder
            ->delete('tx_taskqueue_domain_model_task')
            ->where(
                $queryBuilder->expr()->eq('status', TaskInterface::FINISHED)
            )
            ->executeStatement();
        return count($affectedRows);
    }

```

**Comment by brotkrueml** [comment]
@LinkPool2 Please explain how this problem is related to the example extension manual of the TYPO3 documentation team?

**Comment by brotkrueml** [comment]
I assume, this is related to EXT:taskqueue:
https://extensions.typo3.org/extension/taskqueue

Please open there an issue:
https://github.com/undkonsorten/taskqueue

**Comment by LinkPool2** [comment]
Ooops... Sorry. Wrong window :(
